-- Inserir 35 novos exercícios na biblioteca (5 por categoria)
-- Total final: 70 exercícios (10 por categoria)

-- PEITO (5 novos exercícios)
INSERT INTO public.exercicios_biblioteca (nome, descricao, categoria, imagem_url, imagem_descricao) VALUES
('Supino Declinado com Barra', 'Deite em um banco declinado e empurre a barra para cima, focando na porção inferior do peitoral.', 'Peito', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop&crop=center', 'Homem executando supino declinado com barra em banco declinado, mostrando a posição correta dos braços e ativação da porção inferior do peitoral.'),
('Supino Declinado com Halteres', 'Similar ao supino declinado, mas com halteres para maior amplitude e controle na porção inferior do peito.', 'Peito', 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=300&fit=crop&crop=center', 'Pessoa realizando supino declinado com halteres, demonstrando a amplitude maior do movimento e controle bilateral.'),
('Crucifixo no Banco Inclinado', 'Deite em um banco inclinado e execute o crucifixo com halteres, enfatizando o peitoral superior.', 'Peito', 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=400&h=300&fit=crop&crop=center', 'Atleta executando crucifixo inclinado com halteres, mostrando a abertura dos braços e foco no peitoral superior.'),
('Flexão com Pés Elevados', 'Realize flexões com os pés em uma superfície elevada, aumentando a carga no peito e ombros.', 'Peito', 'https://images.unsplash.com/photo-1571019613540-996a85d8b5f6?w=400&h=300&fit=crop&crop=center', 'Pessoa fazendo flexão com pés elevados em banco, demonstrando a posição inclinada que intensifica o trabalho do peitoral superior.'),
('Pullover com Halter', 'Deite no banco e mova um halter de trás da cabeça até acima do peito, alongando e trabalhando o peitoral.', 'Peito', 'https://images.unsplash.com/photo-1581009137042-c552e485697a?w=400&h=300&fit=crop&crop=center', 'Atleta executando pullover com halter, mostrando o movimento de extensão completa e contração do peitoral.');

-- COSTAS (5 novos exercícios)
INSERT INTO public.exercicios_biblioteca (nome, descricao, categoria, imagem_url, imagem_descricao) VALUES
('Puxada Supinada', 'Puxe a barra com pegada invertida (palmas voltadas para você), enfatizando bíceps e latíssimo.', 'Costas', 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=400&h=300&fit=crop&crop=center', 'Pessoa executando puxada supinada no cabo, mostrando a pegada invertida e ativação dos músculos das costas e bíceps.'),
('Remada com Pegada Supinada', 'Execute a remada curvada com pegada invertida, focando mais nos bíceps junto às costas.', 'Costas', 'https://images.unsplash.com/photo-1571019613540-996a85d8b5f6?w=400&h=300&fit=crop&crop=center', 'Atleta fazendo remada curvada com pegada supinada, demonstrando a posição correta do tronco e ativação muscular.'),
('Puxada em V', 'Use um acessório em V para puxar o cabo, concentrando o movimento no centro das costas.', 'Costas', 'https://images.unsplash.com/photo-1581009137042-c552e485697a?w=400&h=300&fit=crop&crop=center', 'Pessoa executando puxada em V sentada, mostrando o uso do acessório triangular e foco no latíssimo do dorso.'),
('Remada no Smith', 'Realize a remada curvada na máquina Smith, permitindo maior controle e segurança no movimento.', 'Costas', 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=300&fit=crop&crop=center', 'Atleta executando remada curvada na máquina Smith, demonstrando a estabilidade e controle do movimento.'),
('Face Pull no Cabo', 'Puxe o cabo com pegada alta em direção ao rosto, trabalhando a porção posterior dos ombros e trapézio.', 'Costas', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop&crop=center', 'Pessoa fazendo face pull no cabo alto, mostrando a puxada em direção ao rosto e ativação dos deltoides posteriores.');

-- PERNAS (5 novos exercícios)  
INSERT INTO public.exercicios_biblioteca (nome, descricao, categoria, imagem_url, imagem_descricao) VALUES
('Agachamento Frontal', 'Coloque a barra na frente do corpo, sobre os ombros, e agache, enfatizando quadríceps e core.', 'Pernas', 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=400&h=300&fit=crop&crop=center', 'Atleta executando agachamento frontal com barra apoiada na frente dos ombros, mostrando a postura ereta e ativação do core.'),
('Agachamento Hack', 'Use a máquina de hack squat para realizar o movimento, focando nos quadríceps com maior segurança.', 'Pernas', 'https://images.unsplash.com/photo-1581009137042-c552e485697a?w=400&h=300&fit=crop&crop=center', 'Pessoa usando máquina hack squat, demonstrando a posição inclinada e foco nos músculos quadríceps.'),
('Afundo Reverso', 'Dê um passo para trás e desça o joelho traseiro, trabalhando pernas e glúteos com menor impacto nos joelhos.', 'Pernas', 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=300&fit=crop&crop=center', 'Atleta executando afundo reverso, mostrando o passo para trás e descida controlada do joelho.'),
('Cadeira Extensora', 'Sente-se na máquina e estenda as pernas contra a resistência, isolando os quadríceps.', 'Pernas', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop&crop=center', 'Pessoa na cadeira extensora, demonstrando a extensão completa das pernas e isolamento dos quadríceps.'),
('Mesa Flexora', 'Deite na máquina e flexione as pernas, trabalhando os isquiotibiais de forma isolada.', 'Pernas', 'https://images.unsplash.com/photo-1571019613540-996a85d8b5f6?w=400&h=300&fit=crop&crop=center', 'Atleta deitado na mesa flexora, executando flexão das pernas e isolamento dos músculos isquiotibiais.');

-- GLÚTEO (5 novos exercícios)
INSERT INTO public.exercicios_biblioteca (nome, descricao, categoria, imagem_url, imagem_descricao) VALUES
('Glute Bridge com Uma Perna', 'Eleve o quadril com uma perna de cada vez, intensificando o trabalho no glúteo.', 'Glúteo', 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=400&h=300&fit=crop&crop=center', 'Pessoa executando glute bridge unilateral, mostrando a elevação do quadril com uma perna e máxima contração glútea.'),
('Kickback no Cabo', 'Posicione-se no cabo e empurre a perna para trás, contraindo o glúteo em cada repetição.', 'Glúteo', 'https://images.unsplash.com/photo-1581009137042-c552e485697a?w=400&h=300&fit=crop&crop=center', 'Atleta fazendo kickback no cabo, demonstrando a extensão da perna para trás e ativação do glúteo máximo.'),
('Agachamento Búlgaro', 'Apoie uma perna atrás em um banco e agache com a outra, enfatizando glúteos e pernas.', 'Glúteo', 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=300&fit=crop&crop=center', 'Pessoa executando agachamento búlgaro com perna apoiada em banco, mostrando a descida controlada e trabalho glúteo.'),
('Abdução Sentada na Máquina', 'Sente-se na máquina e afaste as pernas contra a resistência, ativando glúteos laterais.', 'Glúteo', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop&crop=center', 'Atleta na máquina de abdução sentada, demonstrando o afastamento das pernas e ativação dos glúteos médios.'),
('Step-Up com Halteres', 'Suba em um banco ou plataforma segurando halteres, focando na contração glútea ao elevar o corpo.', 'Glúteo', 'https://images.unsplash.com/photo-1571019613540-996a85d8b5f6?w=400&h=300&fit=crop&crop=center', 'Pessoa fazendo step-up com halteres, mostrando a subida no banco e contração dos glúteos no movimento.');

-- OMBROS (5 novos exercícios)
INSERT INTO public.exercicios_biblioteca (nome, descricao, categoria, imagem_url, imagem_descricao) VALUES
('Desenvolvimento Arnold', 'Execute o desenvolvimento com halteres girando os punhos durante o movimento, para ativação total dos deltoides.', 'Ombros', 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=400&h=300&fit=crop&crop=center', 'Atleta executando desenvolvimento Arnold, mostrando a rotação dos punhos e ativação completa dos deltoides.'),
('Elevação Lateral com Cabo', 'Eleve o braço lateralmente usando um cabo, mantendo tensão constante nos ombros.', 'Ombros', 'https://images.unsplash.com/photo-1581009137042-c552e485697a?w=400&h=300&fit=crop&crop=center', 'Pessoa fazendo elevação lateral no cabo, demonstrando o movimento lateral e tensão constante nos deltoides.'),
('Elevação Frontal com Barra', 'Eleve uma barra reta à frente até a altura dos ombros, focando na porção anterior do deltoide.', 'Ombros', 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=300&fit=crop&crop=center', 'Atleta executando elevação frontal com barra, mostrando a elevação controlada e foco no deltoide anterior.'),
('Crucifixo Invertido no Cabo', 'Puxe os cabos de baixo para cima e para os lados, trabalhando deltoides posteriores.', 'Ombros', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop&crop=center', 'Pessoa fazendo crucifixo invertido no cabo, demonstrando o movimento de abertura e trabalho dos deltoides posteriores.'),
('Shrug com Halteres', 'Eleve os ombros segurando halteres, contraindo o trapézio no topo do movimento.', 'Ombros', 'https://images.unsplash.com/photo-1571019613540-996a85d8b5f6?w=400&h=300&fit=crop&crop=center', 'Atleta executando shrug com halteres, mostrando a elevação dos ombros e contração do músculo trapézio.');

-- BRAÇOS (5 novos exercícios)
INSERT INTO public.exercicios_biblioteca (nome, descricao, categoria, imagem_url, imagem_descricao) VALUES
('Rosca Scott', 'Execute a rosca em um banco inclinado com apoio, isolando os bíceps e minimizando impulsos.', 'Braços', 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=400&h=300&fit=crop&crop=center', 'Pessoa executando rosca Scott no banco inclinado, mostrando o apoio dos braços e isolamento dos bíceps.'),
('Rosca Concentrada', 'Sente-se e flexione um braço de cada vez com halter, concentrando a contração no bíceps.', 'Braços', 'https://images.unsplash.com/photo-1581009137042-c552e485697a?w=400&h=300&fit=crop&crop=center', 'Atleta fazendo rosca concentrada sentado, demonstrando o movimento unilateral e foco na contração do bíceps.'),
('Tríceps no Banco', 'Apoie as mãos em um banco e desça o quadril, flexionando os braços para trabalhar o tríceps.', 'Braços', 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=300&fit=crop&crop=center', 'Pessoa executando tríceps no banco, mostrando a posição das mãos e descida controlada do corpo.'),
('Tríceps Kickback', 'Incline o tronco e estenda os braços para trás com halteres, focando na contração do tríceps.', 'Braços', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop&crop=center', 'Atleta fazendo tríceps kickback inclinado, demonstrando a extensão dos braços para trás e ativação dos tríceps.'),
('Rosca 21s', 'Realize a rosca direta em 3 fases (7 repetições parciais baixas, 7 parciais altas, 7 completas), para máxima ativação dos bíceps.', 'Braços', 'https://images.unsplash.com/photo-1571019613540-996a85d8b5f6?w=400&h=300&fit=crop&crop=center', 'Pessoa executando rosca 21s com barra, mostrando as diferentes amplitudes do movimento para máxima ativação muscular.');

-- CORE (5 novos exercícios)
INSERT INTO public.exercicios_biblioteca (nome, descricao, categoria, imagem_url, imagem_descricao) VALUES
('Abdominal Bicicleta', 'Deite e alterne toques de cotovelo com joelho oposto, trabalhando oblíquos e reto abdominal.', 'Core', 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=400&h=300&fit=crop&crop=center', 'Pessoa executando abdominal bicicleta no solo, mostrando a alternância de cotovelos e joelhos e ativação dos oblíquos.'),
('Prancha Lateral', 'Apoie-se em um antebraço e mantenha o corpo alinhado lateralmente, ativando oblíquos e core.', 'Core', 'https://images.unsplash.com/photo-1581009137042-c552e485697a?w=400&h=300&fit=crop&crop=center', 'Atleta mantendo prancha lateral, demonstrando o alinhamento corporal e ativação dos músculos oblíquos e core.'),
('Abdominal Canoa', 'Sente-se e eleve pernas e tronco simultaneamente, formando um V, contraindo o abdômen.', 'Core', 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=300&fit=crop&crop=center', 'Pessoa executando abdominal canoa, mostrando a posição em V e máxima contração dos músculos abdominais.'),
('Mountain Climbers', 'Em posição de prancha, traga os joelhos alternadamente ao peito, ativando core e aumentando o gasto calórico.', 'Core', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop&crop=center', 'Atleta fazendo mountain climbers, demonstrando a posição de prancha e movimento alternado dos joelhos.'),
('Rotação com Medicine Ball', 'Sente-se e gire uma bola ou peso de um lado para o outro, trabalhando oblíquos e estabilidade.', 'Core', 'https://images.unsplash.com/photo-1571019613540-996a85d8b5f6?w=400&h=300&fit=crop&crop=center', 'Pessoa executando rotação com medicine ball sentada, mostrando o movimento lateral e trabalho dos oblíquos.');

-- Verificar o total de exercícios por categoria após as inserções
SELECT categoria, COUNT(*) as total_exercicios 
FROM public.exercicios_biblioteca 
GROUP BY categoria 
ORDER BY categoria;