// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxxuvjstpeixxxwcoqrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4eHV2anN0cGVpeHh4d2NvcXJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTExMTcsImV4cCI6MjA2NTU2NzExN30.ihPuRtCKb4Yv2UlK0vJum3JCqhEs0Bc2_B3lUpI1n3g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);